
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.38"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.2"

[prune]
  go-tests = true
  unused-packages = true
